nodeLinker: pnp

packageExtensions:
  "@deck.gl/layers@^9":
      dependencies:
        "@loaders.gl/core": "*"
        "@luma.gl/core": "*"
        "@luma.gl/engine": "*"
  
  "@deck.gl/mesh-layers@^9":
    dependencies:
      "@loaders.gl/schema": "*"
  
  "@deck.gl/widgets@^9":
    dependencies:
      "@deck.gl/core": "^9"

  "@loaders.gl/csv@*":
    dependencies:
      "d3-dsv": "*"
  
  "@loaders.gl/loader-utils@*":
    dependencies:
      "@probe.gl/log": "*"

  "@math.gl/web-mercator@*":
    dependencies:
      "@math.gl/core": "*"